name: homelab_panel
description: HomeLab 的平板控制端
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true
